import { Animate } from '../animate.js';

export const cookieUpdateMethods = {
  /**
   * Updates generated HTML for a cookie.
   * @param {*} cookie Cookie data.
   */
  updateHtml(cookie) {
    if (!this.isGenerated) {
      return;
    }
    this.cookie = cookie;
    if (!this.baseHtml.querySelector('form')) {
      this.updateCompactHtml();
      return;
    }
    const oldCookie = this.readCookieFormState();
    this.updateChangedFields(oldCookie);
  },

  readCookieFormState() {
    const expiration = new Date(
      this.baseHtml.querySelector('#expiration-' + this.guid).value
    ).getTime();
    return {
      name: this.getFieldValue('name'),
      value: this.getFieldValue('value'),
      domain: this.getFieldValue('domain'),
      path: this.getFieldValue('path'),
      sameSite: this.getFieldValue('sameSite'),
      hostOnly: this.getFieldChecked('hostOnly'),
      session: this.getFieldChecked('session'),
      secure: this.getFieldChecked('secure'),
      httpOnly: this.getFieldChecked('httpOnly'),
      expirationDate: isNaN(expiration) ? undefined : expiration / 1000,
    };
  },

  getFieldValue(field) {
    return this.baseHtml.querySelector(`#${field}-${this.guid}`).value;
  },

  getFieldChecked(field) {
    return this.baseHtml.querySelector(`#${field}-${this.guid}`).checked;
  },

  updateChangedFields(oldCookie) {
    const checks = [
      ['name', 'updateName'],
      ['value', 'updateValue'],
      ['domain', 'updateDomain'],
      ['path', 'updatePath'],
      ['expirationDate', 'updateExpiration'],
      ['sameSite', 'updateSameSite'],
      ['hostOnly', 'updateHostOnly'],
      ['session', 'updateSession'],
      ['secure', 'updateSecure'],
      ['httpOnly', 'updateHttpOnly'],
    ];
    if (this.cookie.name !== oldCookie.name) {
      this.updateName();
    }
    this.updateExtraInfo();
    checks.slice(1).forEach(([field, method]) => {
      if (this.cookie[field] !== oldCookie[field]) {
        this[method]();
      }
    });
  },

  /**
   * Updates compact markup generated by toCompactHtml.
   */
  updateCompactHtml() {
    this.baseHtml.dataset.name = this.cookie.name;
    this.updateOptionalText('.cookie-name', this.cookie.name || '(unnamed)');
    this.updateOptionalText(
      '.cookie-value',
      this.cookie.value || '(empty value)'
    );
    this.updateOptionalText(
      '.cookie-meta',
      [this.cookie.domain, this.cookie.path].filter(Boolean).join('  ')
    );
    this.animateChangeOnNode(this.baseHtml);
  },

  updateOptionalText(selector, text) {
    const node = this.baseHtml.querySelector(selector);
    if (node) {
      node.textContent = text;
    }
  },

  updateName() {
    this.baseHtml.setAttribute('data-name', this.cookie.name);
    this.updateInputValue('name', this.cookie.name);
    this.baseHtml.querySelector('.header-name').textContent = this.cookie.name;
    this.animateHeaderAndField('name');
  },

  updateExtraInfo() {
    const headerExtraInfo = this.baseHtml.querySelector('.header-extra-info');
    headerExtraInfo.textContent = this.getExtraInfoValue();
    headerExtraInfo.title = this.getExtraInfoTitle();
    this.animateChangeOnNode(this.baseHtml.querySelector('.header'));
  },

  updateValue() {
    this.updateInputValue('value', this.cookie.value);
    this.animateHeaderAndField('value');
  },

  updateDomain() {
    this.updateInputValue('domain', this.cookie.domain);
    this.animateHeaderAndField('domain');
  },

  updatePath() {
    this.updateInputValue('path', this.cookie.path);
    this.animateHeaderAndField('path');
  },

  updateExpiration() {
    this.updateInputValue('expiration', this.formatExpirationForDisplay());
    this.animateHeaderAndField('expiration');
  },

  updateSameSite() {
    this.updateInputValue('sameSite', this.cookie.sameSite);
    this.animateHeaderAndField('sameSite');
  },

  updateHostOnly() {
    this.updateInputChecked('hostOnly', this.cookie.hostOnly);
    this.afterHostOnlyChanged(this.cookie.hostOnly);
    this.animateHeaderAndField('hostOnly');
  },

  afterHostOnlyChanged(inputValue) {
    this.baseHtml.querySelector('#domain-' + this.guid).disabled = inputValue;
  },

  updateSession() {
    this.updateInputChecked('session', !this.cookie.expirationDate);
    this.afterSessionChanged();
    this.animateHeaderAndField('session');
  },

  afterSessionChanged(inputValue) {
    const expirationInput = this.baseHtml.querySelector(
      '#expiration-' + this.guid
    );
    expirationInput.disabled = inputValue;
    if (inputValue) {
      expirationInput.value = 'No Expiration';
      return;
    }
    if (!this.cookie.expirationDate) {
      this.cookie.expirationDate =
        new Date(Date.now() + 1 * (60 * 60 * 1000)).getTime() / 1000;
    }
    expirationInput.value = this.formatExpirationForDisplay();
  },

  updateSecure() {
    this.updateInputChecked('secure', this.cookie.secure);
    this.animateHeaderAndField('secure');
  },

  updateHttpOnly() {
    this.updateInputChecked('httpOnly', this.cookie.httpOnly);
    this.animateHeaderAndField('httpOnly');
  },

  updateInputValue(field, value) {
    this.baseHtml.querySelector(`#${field}-${this.guid}`).value = value;
  },

  updateInputChecked(field, checked) {
    this.baseHtml.querySelector(`#${field}-${this.guid}`).checked = checked;
  },

  animateHeaderAndField(field) {
    this.animateChangeOnNode(this.baseHtml.querySelector('.header'));
    this.animateChangeOnNode(
      this.baseHtml.querySelector(`#${field}-${this.guid}`)
    );
  },

  removeHtml(callback = null) {
    if (this.isRemoving) {
      return;
    }
    this.isRemoving = true;
    Animate.toggleSlide(this.baseHtml, () => {
      this.baseHtml.remove();
      this.baseHtml = null;
      this.isRemoving = false;
      if (callback) {
        callback();
      }
    });
  },

  animateChangeOnNode(node) {
    node.classList.remove('anim-value-changed');
    setTimeout(() => {
      node.classList.add('anim-value-changed');
    }, 20);
  },

  showSuccessAnimation() {
    if (this.baseHtml) {
      this.animateSuccessOnNode(this.baseHtml);
    }
  },

  animateSuccessOnNode(node) {
    node.classList.remove('anim-success');
    setTimeout(() => {
      node.classList.add('anim-success');
    }, 20);
  },
};
